### ISSUE TITLE
how to get comments ?

### ISSUE THREAD

**Issue by cocotyty** [goccmack/gogll#12]
Lexer's `Tokens` not contains comments.

**Comment by goccmack** [comment]
I am not sure that I understand your question exactly. The section [Lexical Rules](https://github.com/goccmack/gogll/blob/master/gogll.md#lexical-rules) of the [grammar](https://github.com/goccmack/gogll/blob/master/gogll.md) specifies how to define ignored tokes. If you want to ignore comments, that is how you would do it. There is also an example of c-style line and block comments.

I hope that helps.
