### ISSUE TITLE
Please support the go module correctly.

### ISSUE THREAD

**Issue by taichi** [goccmack/gogll#14]
I followed the documentation and ran `go get github.com/goccmack/gogll` and it installed v1.0.4 instead of the latest version v3.2.2.

This is because the major version suffix is not given to the module name, even though the major version of gogll is 2 or higher.

For more details, please refer to the following document.
https://golang.org/ref/mod#module-path
https://github.com/golang/go/wiki/Modules#semantic-import-versioning

To fix this, change the module name declared in the go.mod file as follows

> module github.com/goccmack/gogll/v3

In addition, make the same change to all import statements.

**Comment by goccmack** [comment]
Thank you @taichi for bringing this to my attention. 

Install gogll v3 by: 

go get github.com/goccmack/gogll/v3
