### ISSUE TITLE
Generated files are set as executable

### ISSUE THREAD

**Issue by Joakker** [goccmack/gogll#15]
As stated in the title, and at least on linux, files generated using gogll are marked as executable despite being just plain source code. Is there a particular reason behind this?

This isn't a huge problem, but it does stand out. For reference, here is a screenshot of the file tree. The green files have all been generated by the tool and haven't been tampered with.

![image](https://user-images.githubusercontent.com/51842726/116770143-7e972c80-aa0f-11eb-835b-631b75050ed6.png)

**Comment by goccmack** [comment]
Thanks @Joakker for reporting this. It is fixed in v3.2.7.

**Comment by Joakker** [comment]
Thanks :smiley:
