### ISSUE TITLE
Support For Named Unicode Character Classes

### ISSUE THREAD

**Issue by nbcarey** [goccmack/gogll#17]
I'm fiddling with `gogll` and I like it. Much cleaner than `goyacc`. I especially like the ability to embed the grammar in a CommonMark/Markdown file. A lovely way to document the grammar.

It would be nice/useful if `gogll` supported
- Unicode [named character classes](https://unicode.org/reports/tr18/#General_Category_Property)
- at least some [Unicode character properties](https://www.unicode.org/reports/tr44/tr44-28.html) (e.g., `ID_Start` and `ID_Continue`)
- arbitrary Go regular expressions as a means of defining terminals.

Currently, the only predefined character classes you support are
- `letter`: Unicode character class `L`|`Letter`, which comprises the the following Unicode character classes:
    - `Lu` | `Uppercase Letter`
    - `Ll` | `Lowercase Letter`
    - `Lt`| `Titlecase Letter`
    - `Lm` | `Modifier Letter`
    - `Lo` | `Other Letter`
- `upcase`: Unspecified, but I suspect this is the Unicode character class `Lu`| `Uppercase Letter`.
- `lowcase`: Unspecified, but I suspect this is the Unicode character class `Ll`|`Lowercase Letter`.
- `number`: Unicode character class `N`|`Number, which comprises the following Unicode character classes
    - `Nd`|`Decimal Digit Number`
    - `Nl`|`Letter Number`
    - `No`|`Other Number`

This makes writing parsers for some languages difficult (and the resulting parsers brittle should Unicode add new characters).

For instance, the [Javascript/Ecmascript specification for an _identifier_](https://tc39.es/ecma262/#sec-names-and-keywords) is defined in terms of those Unicode characters having the `ID_Start` and `ID_Continue` properties:

![C2B0CE86-3B65-44AE-B461-024101D42504](https://user-images.githubusercontent.com/6518145/184518517-1ce95702-b5be-417d-8c69-86ef43995d87.png)

And the Go programming language defines the [`identifier` production](https://go.dev/ref/spec#Identifiers) as
```
identifier = letter { letter | unicode_digit } .

letter        = unicode_letter | "_" .

unicode_letter = /* a Unicode code point categorized as "Letter" */ .
unicode_digit  = /* a Unicode code point categorized as "Number, decimal digit" */ .
```

No having support for Unicode named character classes or properties makes it difficult to write a parser for such languages. The Unicode  `Number, decimal digit` class comprises some 650 [discontiguous] code points. I have no idea how many code points are in the `ID_Start` category (a lot), and `ID_Continue adds to it. From [Unicode® Standard Annex #31: Unicode Identifier and Pattern Syntax](https://unicode.org/reports/tr31/#Default_Identifier_Syntax):

![90C65CC8-373E-499B-9D25-B6841263438C](https://user-images.githubusercontent.com/6518145/184518729-a5729c3e-d4a3-4e27-967a-f4074d6e298a.png)

As you can see, adding support for this sort of stuff would be useful.

**Comment by goccmack** [comment]
When I originally made gogll I hoped that the Go standard libraries would in future have better support for Unicode classes. I see that the unicode package now has a large number of RangeTable variables defined.

I prefer to use only the go standard library in generated code. Would the range table options in the unicode package of go 1.19 standard library be sufficient for your purposes?

**Comment by nbcarey** [comment]
Possibly. I'm not all that familiar with how they work, though. It's a compact way of describing [large] sets of  Unicode characters, correct?

[And yes, I agree with you that the Go standard packages' support for Unicode leaves something to be desired.

**Comment by goccmack** [comment]
The grammar now supports basic Unicode sets which which support the Unicode character properties supported in Go package unicode. See test/lex/lex6/lex6.md for an example. Because I didn't want to break compatibility with existing gogll grammars, I didn' t change the handling of regular expressions.
Let me know if this works for you.
