### ISSUE TITLE
backslash used as operator (integer division)

### ISSUE THREAD

**Issue by ghost** [goccmack/gogll#23]
in BASIC, the backslash character (\\) is used for integer division on float numbers. When I try to use it, I get an error. Here is the code:

```
package "BUG_REPPORT"

Expr
	: number "\\" number;      	    								
```

And here is the message : 
```
Parse Errors:
Parse Error: SyntaxRule : nt : ∙SyntaxAlternates ;  I[4]=number (36,42) number at line 6 col 7
Expected one of: [empty,nt,string_lit,tokid]
```

I also tried:

```
package "BUG_REPPORT"

Expr
	: number intDivOp number;      	    								

intDivOp: '\\';

```
This gives me the same error as above.

**Comment by goccmack** [comment]
gogll does not allow escaped chars in string_lit. You can define and use a division token as in the following grammar:

```
package "test"

div : '\\' ;

int : number {number} ;

Expr : int div int ;
```

You can test the grammar as follows:

package test

import (
	"test/lexer"
	"test/parser"
	"testing"
)

const input = `12 \ 4`

func Test1(t *testing.T) {
	l := lexer.New([]rune(input))
	_, errs := parser.Parse(l)
	if len(errs) > 0 {
		t.Fail()
	}
}

> go test -v   
=== RUN   Test1
--- PASS: Test1 (0.00s)
PASS
ok      test    0.414s

**Comment by ghost** [comment]
Thank you for your suggestion.
