### ISSUE TITLE
Bug with using "\""

### ISSUE THREAD

**Issue by acanalis** [goccmack/gogll#5]
I'm using gogll version: 
```
> gogll -version
gogll v3.2.0
```
If I run the following simple program:
```
package "hello"

Aa: "\"";
```
It fails with:
```
> gogll jsony.md
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
github.com/goccmack/gogll/ast.(*CharLiteral).Char(0xc00000c5c0, 0x1)
        /home/agus/go/src/github.com/goccmack/gogll/ast/lex.go:171 +0x1d9
github.com/goccmack/gogll/lex/items/event.Subset(0x68cc20, 0xc00000c5c0, 0x68cc20, 0xc00000c5c0, 0xc00000c5c0)
        /home/agus/go/src/github.com/goccmack/gogll/lex/items/event/event.go:105 +0x2a5
github.com/goccmack/gogll/lex/items.(*Set).nextSets(0xc00011e1c0, 0x0, 0x0, 0x0)
        /home/agus/go/src/github.com/goccmack/gogll/lex/items/items.go:179 +0x119
github.com/goccmack/gogll/lex/items.New(0xc00005c280, 0xc00000c5a0)
        /home/agus/go/src/github.com/goccmack/gogll/lex/items/items.go:65 +0x24f
main.main()
        /home/agus/go/src/github.com/goccmack/gogll/main.go:84 +0x21c
```
If this isn't a bug but a conceptual problem, it should probably fail with a more informative error.  

Thanks for the project, it's very nice to play with BNF!

**Comment by goccmack** [comment]
@acanalis Thanks for reporting this. V3 does not deal correctly with escaped characters in string literals. I am working on a version that fixes the problem.

**Comment by goccmack** [comment]
@acanalis v3.2.1 fixes this issue for Go. This version does not support Rust. Please let me know if you need Rust support

**Comment by acanalis** [comment]
Thanks, Go is okay ! I'd like to contribute a JSON example is that's fine with you. See you then!

**Comment by goccmack** [comment]
@acanalis That would be great! Thank you.
